<?
/*
phpRADmin is developped with GPL Licence 2.0 :
http://www.gnu.org/licenses/gpl.txt
Developped by : Toni de la Fuente (blyx)

For information : toni@blyx.com
*/function print_header($handle, $firstname, $lastname)
{
	$time = date("F j, Y, g:i a");
	$by = $firstname . " " . $lastname;
	$str  = "###################################################################\n";
	$len = strlen($str); // Get line lenght
	$str .= "#                                                                 #\n";
	$str .= "#                       GENERATED BY OREON                        #\n";
	$str .= "#                                                                 #\n";
	$str .= "#               Developped by :                                   #\n";
	$str .= "#                   - Julien Mathis                               #\n";
	$str .= "#                   - Romain Le Merlus                            #\n";
	$str .= "#                                                                 #\n";
	$str .= "#                          www.oreon.org                          #\n";
	$str .= "#                For information : contact@oreon.org              #\n";
	$str .= "###################################################################\n\n";
	$str .= "###################################################################\n";
	$str .= "#                                                                 #\n";
	$str .= "#         Last modification " . $time;
	
	$len_time = strlen($time);
	$res = $len - 28 - $len_time - 2;
	
	// Add space to put text on center
	for ($i = 0; $i != $res; $i++)
		$str  .= " ";
	
	$str .= "#\n";
	$str .= "#         By " . $by;
	$len_by = strlen($by);
	$res = $len - 13 - $len_by - 2;
	
	// Add space to put text on center
	for ($i = 0; $i != $res; $i++)
		$str  .= " ";
	$str .= "#\n";
	$str .= "#                                                                 #\n";
	$str .= "###################################################################\n\n";
	fwrite($handle, $str);
}

// Create File, print header and return handle. 

function create_file($filename, $firstname, $lastname)
{
	if (!$handle = fopen($filename, 'w')) {         
    	echo "can t open " . $filename;         
    	exit;
	}
   print_header($handle, $firstname, $lastname);
   return $handle;
}

// write data into the file

function write_in_file($handle, $content, $filename)
{
	if (strcmp($content, "") && !fwrite($handle, $content)) {
		echo "can t open " . $filename;
		exit;
	}
}

// Put text in good format

function print_line($data1, $data2)
{
  $len = strlen($data1);
  if ($len <= 9)
    return "\t" . $data1 . "\t\t\t\t" . $data2 . "\n";
  else if ($len > 9 && $len <= 18)
    return "\t" . $data1 . "\t\t\t" . $data2 . "\n";
  else if ($len >= 19 && $len <= 27)
    return "\t" . $data1 . "\t\t" . $data2 . "\n";
  else if ($len > 27)
    return "\t" . $data1 . "\t" . $data2 . "\n";
}

?>